on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Configure Git
        run: |
          git config --global user.email "juka.mebaj@gmail.com"
          git config --global user.name "jukerah"
      - run: npm install
      - run: npm version minor
      - run: git push --tags "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}